@baseUrl = http://localhost:3000/movies
### Recuperar las peliculas
GET {{baseUrl}}

### recuperar pelicula por ID
GET {{baseUrl}}/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### recuperar peliculas por  un genero
GET {{baseUrl}}?genre=action


### Creando un recurso
POST {{baseUrl}} HTTP/1.1
content-type: application/json

{
  "title": "Spider-Man",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una pelicula con patch

PATCH {{baseUrl}}/a3787de0-0183-43c1-a486-cec0d9e586b2 HTTP/1.1
content-type: application/json

{
  "title": "Spider-Man",
  "year": 2000
}

### Borrar una Pelicula 
DELETE {{baseUrl}}/a3787de0-0183-43c1-a486-cec0d9e586b2 HTTP/1.1
content-type: application/json 