@baseUrl = http://localhost:3000/movies
### Recuperar las peliculas
GET {{baseUrl}}

### recuperar pelicula por ID
GET {{baseUrl}}/650c78e76af538407ec879b1

### recuperar peliculas por  un genero
GET {{baseUrl}}?genre=action


### Creando un recurso
POST {{baseUrl}} HTTP/1.1
content-type: application/json

{
  "title": "Spider-Man",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Actualizar una pelicula con patch

PATCH {{baseUrl}}/650c78e76af538407ec879b2 HTTP/1.1
content-type: application/json

{
  "title": "Fast and Furios 10",
  "year": 2023
}

### Borrar una Pelicula 
DELETE {{baseUrl}}/650c78e76af538407ec879b1 HTTP/1.1
content-type: application/json 